version: '4'
services:
  php-apache:
    ports: 
      - "81:80"
    build: "./build/php"
    volumes:
      - ./app:/var/www/html
    env_file:
      - .env
  mysql:
    ports:
      - "3306:3306"
    build: './build/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: 'php-db'
    volumes:
      - dbData:/var/lib/mysql
volumes:
    app:
    dbData:


